linters:

  IdSelector:
    enabled: false

  QualifyingElement:
    enabled: true
    severity: error
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false
