name: a-instantsearch
root: ~/local/www/algolia/javascript/instantsearch.js/
startup_window: 1

windows:
  - vim: 
      layout: even-horizontal
      panes: 
        - chrome http://localhost:8080/
        - vdl
  - server: npm run dev
