name: a-reactjs
root: ~/local/www/algolia/projects/react
startup_window: 1

windows:
  - vim: 
      layout: even-horizontal
      panes: 
        - chrome http://localhost:4004/
        - vdl
  - server: 
      layout: even-horizontal
      panes:
        - cd ./docs && jekyll serve --watch --port 4004
