name: a-reactparts
root: ~/local/www/algolia/projects/react-parts
startup_window: 1

windows:
  - vim: 
      layout: even-horizontal
      panes:
        - 
        - 
  - server:
      layout: even-horizontal
      panes:
        - PORT=8081 npm run live
        - npm run js:watch
