name: perso-roleplay-pixelastic
root: ~/local/www/pixelastic.com/roleplay.pixelastic.com/
startup_window: 1

windows:
  - vim: 
      layout: even-horizontal
      panes: 
        - chrome http://localhost:4001/
        - # Right pane
  - server: 
      layout: even-horizontal
      panes: 
        - npm run serve
